### ISSUE TITLE
unexpected data type after conversion from blaze to pandas DataFrame

### ISSUE THREAD

**Issue by inkrement** [blaze/blaze#1595]
I have to import a data table from a mysql database, which works fine. But after converting it to a pandas DataFrame some integer columns are int64 types, but some are "python objects". I don't know exactly why, but it seems like all int columns that contain missing values are converted to python objects instead of int64. Is there a proper way to handle this or force/convert the data type?

```python
some_table = bz.into(pd.DataFrame, database.sometable)
some_table.dtypes
```
> t               int64
> value       object
> dtype: object

**Comment by gryBox** [comment]
What version of blaze are you running? `bz.into()` has been deprecated since 2015. See [here](https://www.continuum.io/blog/developer/whats-new-blaze)

I believe you want to use [odo ](http://odo.readthedocs.io/en/latest/) for moving data from one data container to another - see [this ](http://stackoverflow.com/questions/30897932/error-accessing-spark-with-blaze )stack overflow answer.

That being said mysql and pandas dtypes do not play well with each other depending on the python cursor interface you are using and pandas version you are using.

**Comment by inkrement** [comment]
@gryBox I updated the script, but I have the same problem.

**Comment by gryBox** [comment]
> That being said mysql and pandas dtypes do not play well with each other depending on the python cursor interface you are using and pandas version you are using.

 @inkrement I went through a similar issues when using mysql, sqlachemy, blaze, odo, pandas and dask.   

What did you update? 
what version of pandas are you using?
are you using mysql.connector or some other cursor?
are you explicitly defining the datashape paramater? 
do those columns have `nan`'s. 
are you married to mysql?

There are a couple paths to try depending on your answers.

**Comment by inkrement** [comment]
| changed
```
aggregated_videos = bz.into(pd.DataFrame, database.videos_weekly)
```
to
```
aggregated_videos = odo(database.videos_weekly, pd.DataFrame)
```

I use **pandas 0.19.0** and the following connection string, so I guess it's the mysql.connector:
```
datashape.coretypes._canonical_string_encodings.update({"utf8_general_ci": "U8"})
database = bz.Data('mysql://root@domain.com/db?charset=utf8mb4')
```

Those columns have `nan`'s. All other columns without `nan`s are int64 datatypes as expected. Actually it's not mysql, it's memsql. I am not married to this database, but I have a slow disk and a lot of memory and so I wanted to use an in memory database. What would you recommend?

**Comment by gryBox** [comment]
I am not at all familiar with memsql.  Again the issue is dtype mapping...
did you try ` coerce_float=False` ?  [here](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql.html?highlight=read%20sql#pandas.read_sql)

I think this is the [stack overflow](http://stackoverflow.com/questions/34383000/pandas-to-sql-all-columns-as-nvarchar) result that lead me to a solution. 

What is the size of your data in a pandas df?  hdf fixed format is fast.

**Comment by inkrement** [comment]
I exported the mysql to a csv file and I use pandas to import it. Now it works (sadly without blaze).

**Comment by gryBox** [comment]
lol ... that is actually the fastest way io with mysql...

Itay Livni

**Comment by inkrement** [comment]
@gryBox do you mean csv is the best way to import/export from mysql? ok, maybe this is true, but it's not very comfortable. Would be great if I can use the mysql-api directly...
